### ISSUE TITLE
After creating a new account, the current subscription plan information shows null

### ISSUE THREAD

**Issue by NicolJamie** [RedRockDigital/rrd-api#85]

**Comment by NicolJamie** [comment]
@thomaspalmer I'm not entirely sure that's the case on this one, I've test this multiple times.

Can you produce some screenshots?

**Comment by thomaspalmer** [comment]
@NicolJamie Steps to reproduce:

- Register for a new account through the registration page
- Active the account
- Log into the new account
- Go to manage team
- Go to billing
- Observe.

Also, where it say's default should we know show free?

![Screenshot 2023-01-21 at 06 31 51](https://user-images.githubusercontent.com/2190634/213847028-26e0035a-d73d-4322-9d0f-554ad65942d4.png)

**Comment by thomaspalmer** [comment]
Just noticed the payment information... will raise a separate issue.

**Comment by thomaspalmer** [comment]
Sorry, didn't realise that this was a part of the webhook. Disregard.
